package com.cleanroommc.groovyscript.api.documentation.annotations;

import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;
import java.lang.reflect.Method;

/**
 * Marks the given Method as a Recipe Builder method, indicating it returns a Recipe Builder class and is used inside a Recipe Builder.<br>
 * A Recipe Builder is a class which follows the Builder design pattern, where each step of the builder returns the builder class,
 * allowing chaining of methods to quickly and cleanly create complicated objects which may or may not require some values.<br>
 * The field element is autogenerated to be equal to the method name by default.
 * <ul>
 *     <li>{@link #field()} is an array that defaults to {@link Method#getName()} if not overridden, and indicates the target field(s) that the method modifies.</li>
 *     <li>{@link #priority()} is an integer that influences the sorting of the {@link RecipeBuilderMethodDescription} relative to other {@link RecipeBuilderMethodDescription}s.</li>
 * </ul>
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.METHOD)
public @interface RecipeBuilderMethodDescription {

    /**
     * An array of all fields this method modifies. By default, it checks for a field with the same name as the method.
     *
     * @return an array of the names of the field calling the method modifies. Defaults to the method name
     */
    String[] field() default {};

    /**
     * Priority of the method, relative to other {@link RecipeBuilderMethodDescription}s modifying the shared {@link Property}.
     * Priorities sort entries such that lowest is first, then by the length of {@link Method#getName()}, then by {@link String#compareToIgnoreCase} of {@link Method#getName()}.
     *
     * @return the method priority
     */
    int priority() default 1000;

}
