
mods.de.Fusion.recipeBuilder()
    .catalyst('<minecraft:diamond>')
    .input('<ore:ingotIron>')
    .input('<ore:ingotIron>')
    .input('<minecraft:dirt>')
    .input('<minecraft:grass>')
    .input('<minecraft:grass>')
    .input('<minecraft:dirt>')
    .input('<ore:ingotGold>')
    .input('<ore:ingotGold>')
    .output('<minecraft:nether_star>')
    .energy(100000)
    .tierWyvern()
    .register()