
mods.de.Fusion.recipeBuilder()
    .catalyst(item('minecraft:diamond'))
    .input(ore('ingotIron'))
    .input(ore('ingotIron'))
    .input(item('minecraft:dirt'))
    .input(item('minecraft:grass'))
    .input(item('minecraft:grass'))
    .input(item('minecraft:dirt'))
    .input(ore('ingotGold'))
    .input(ore('ingotGold'))
    .output(item('minecraft:nether_star'))
    .energy(100000)
    .tierWyvern()
    .register()