// MODS_LOADED: bewitchment
println 'mod \'bewitchment\' detected, running script'

mods.bewitchment.oven.removeByOutput(item('minecraft:bread'))
mods.bewitchment.oven.recipeBuilder()
    .input(item('minecraft:clay'))
    .output(item('minecraft:diamond'))
    .requiresJar(false)
    .byproduct(item('minecraft:gold_nugget'))
    .byproductChance(0.2f)
    .register()

mods.bewitchment.frostfire.removeByOutput(item('bewitchment:cold_iron_ingot'))
mods.bewitchment.frostfire.recipeBuilder()
    .input(item('minecraft:water_bucket'))
    .output(item('minecraft:ice'))
    .register()

mods.bewitchment.distillery.remove(resource('bewitchment:bottled_frostfire'))
mods.bewitchment.distillery.recipeBuilder()
    .input(item('minecraft:glass_bottle'))
    .input(item('minecraft:snow'))
    .input(item('bewitchment:cleansing_balm'))
    .input(item('bewitchment:fiery_unguent'))
    .output(item('bewitchment:bottled_frostfire'))
    .output(item('bewitchment:empty_jar') * 2)
    .register()

mods.bewitchment.spinningWheel.remove(resource('bewitchment:cobweb'))
mods.bewitchment.spinningWheel.recipeBuilder()
    .input(item('minecraft:string'))
    .input(item('minecraft:string'))
    .input(item('minecraft:string'))
    .input(item('minecraft:string'))
    .output(item('minecraft:web'))
    .output(item('minecraft:web'))
    .register()

mods.bewitchment.cauldron.remove(resource('bewitchment:catechu_brown'))
mods.bewitchment.cauldron.recipeBuilder()
    .input(ore('logWood'))
    .input(item('minecraft:deadbush'))
    .input(item('minecraft:dye', 3))
    .output(item('bewitchment:catechu_brown'))
    .register()