mods.groovyscript.furnace.add(ore('ingotIron'), item('minecraft:diamond'))

mods.groovyscript.test.recipeBuilder()
        .append('H')
        .append('e')
        .append('l')
        .append('l')
        .append('o')
        .register()

mods.groovyscript.test.recipeBuilder()
        .append('W')
        .append('o')
        .append('r')
        .append('l')
        .append('d')
        .register()
